### ISSUE TITLE
Package for Arch Linux

### ISSUE THREAD

**Issue by ncoder-1** [jaybosamiya/busysteg#2]
Hi,

Do you mind if I make a package for Arch Linux in the the [AUR](aur.archlinux.org) (Arch User Repo) so anyone can compile/install easily in Arch from your git source?  It would be named "busysteg-git".

**Comment by jaybosamiya** [comment]
Sure, go ahead :smile:

**Comment by ncoder-1** [comment]
Done!  See it here:  https://aur.archlinux.org/packages/busysteg-git/

It will compile from your latest HEAD.  Also included your personal license.

**Comment by jaybosamiya** [comment]
Thanks :smile:
